version: '3.1.8'
services:
  springboot-app:
    build:
      context: /home/hjhgjhgjhg/Downloads/backendinterview
      dockerfile: /home/hjhgjhgjhg/Downloads/backendinterview/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - mobiauto-net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/mobiauto
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - JWT_TOKEN_EXPIRACAO=60
      - JWT_TOKEN_ASSINATURA=dqY8HUEMqBoReYjU35ge/qhdFunjxzDipEYLrxXTgMU=
    depends_on:
      - postgres-db
    command: ["/wait-for-it.sh postgres-db:5432 -t 60 -- java -Djava.security.egd=file:/dev/./urandom -jar /app/backendinterview-0.0.1-SNAPSHOT.jar
"]

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    networks:
      - mobiauto-net
    environment:
      - POSTGRES_DB=mobiauto
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

networks:
  mobiauto-net:
