version: '3'
services:
  springboot-app:
    image: backendinterview:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/mobiauto
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mobiauto
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
